import 'package:flutter/material.dart';
import 'package:npa_user/model/models.dart';
import 'package:npa_user/repositories/district/district.dart';

class DistrictRepository {
  final DistrictApiClient districtApiClient;
  List<District> _districts = [
    District(
      id: 1,
      code: "",
      name: "Biakoye ",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Jasikan",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Kadjebi",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Krachi East",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Krachi Nchumuru",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Krachi West",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Nkwata North",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Nkwata South",
      regionId: 1,
    ),
    District(
      id: 1,
      code: "",
      name: "Atebubu Amantin",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Kintampo North",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Kintampo South",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Nkoranza South",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Nkoranza North",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Pru East",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Pru West",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Sene  East",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Sene  West",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Techiman",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Techiman North",
      regionId: 4,
    ),
    District(
      id: 1,
      code: "",
      name: "Asunafo North",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Asunafo South",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Asutifi North",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Asutifi South",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Tano North",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Tano South",
      regionId: 3,
    ),
    District(
      id: 1,
      code: "",
      name: "Banda",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Berekum",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Dormaa Central",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Dorma East",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Dormaa West",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Juman North",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Juman  South",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Sunyani",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Sunyani West",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Tain",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Wenchi",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Berekum West",
      regionId: 2,
    ),
    District(
      id: 1,
      code: "",
      name: "Bunkpurugu Nyankpanduri",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "Cheriponi",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "East Mamprusi",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "Mamprugu Moagduri",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "West Mamprusi",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "Yunyoo-Nasuan",
      regionId: 5,
    ),
    District(
      id: 1,
      code: "",
      name: "Bole",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "Central Gonja",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "East Gonja",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "North Gonja",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "Sawla-Tuna-Kalba",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "West Gonja",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "North East Gonja",
      regionId: 6,
    ),
    District(
      id: 1,
      code: "",
      name: "Aowin",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Bia East",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Bia West",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Bibiani-Anhwiaso Bekwai",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Bodi",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Juaboso",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Sefwi Akontombra",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Sefwi Wiawso",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Suaman",
      regionId: 7,
    ),
    District(
      id: 1,
      code: "",
      name: "Ahanta",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Amenfi Central",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Wassa Amenfi East",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Amenfi West",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Ellembelle",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Jomoro",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Mpohor",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Nzema East",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Presta-Huni Valley",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Secondi Takoradi",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Shama",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Tarkwa Nsuaem",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Wassa  East",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Effia Kwesimintim",
      regionId: 8,
    ),
    District(
      id: 1,
      code: "",
      name: "Adaklu",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Afadzato South",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Agotime Ziope",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Akatsi North",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Akatsi South",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Central Tongu",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Ho",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Hohoe",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Keta",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Ketu North",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Ketu South",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Kpando",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "North Dayi",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "North Tongu",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "South Dayi",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "South Tongu",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Anloga",
      regionId: 9,
    ),
    District(
      id: 1,
      code: "",
      name: "Accra",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Adda West",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Adda East",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Adentan",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ashaiman",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ga Central",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ga South",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ga East",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ga West",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "La Dade Kotopon",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ledzekuku",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "La Nkwatanang Madina",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ningo Pampram",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Shai Osudoku",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Tema",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Kpone Katamanso",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Okaikwei North",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ablekuma North",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ablekuma West",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ayawaso East",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ayawaso North",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ayawaso west",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ga North",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Weija-Gbawe",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Tema West",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Krowor",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Korle Klottey",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ablekuma Central",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Ayawaso Central",
      regionId: 10,
    ),
    District(
      id: 1,
      code: "",
      name: "Akuapem North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Akuapem South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Akyemansa",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Asuogyaman",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Atiwa West",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Ayensuno",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Brim Central",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Brim North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Brim South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Denkyembour",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Abuakwa South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Fanteakwa North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwaebibirem",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Ellembelle",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwahu Afram Plains North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwahu Afram Plains South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwahu East",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwahu South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwahu West",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Lower Manya Krobo",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "New Juaben South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Nsawam Adoagyiri",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Suhum",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Upper Manya Krobo",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Upper West Akim",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "West Akim",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Yilo Krobo",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Okere",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Atiwa East",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Fanteakwa South",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Asene Manso Akroso",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Abuakwa North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "New Juaben North",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Achiase",
      regionId: 11,
    ),
    District(
      id: 1,
      code: "",
      name: "Adansi North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Adansi South",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Afigya Kwabre",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Ahafo Ano North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Ahafo Ano South",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Amanse Central",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Amanse West",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Asante Akim Central",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Asante Akim North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Asokore Mampong",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Atwima Kwanwoma",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Atwima Mponua",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Atwima Nwabiagya",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Bekwai",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Bekwai Freho",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Bosomtwe",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Ejisu",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Ejura Sekyedumase",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Kumasi",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwabre East",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Mampong",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Obuasi",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Offinso",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Offinso North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Sekyere Afram Plains",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Sekyere Central",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Sekyere East",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Sekyere Kumawu",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Sekyere South",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Oforikrom",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Kwadaso",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Old Tafo",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Asokwa",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Suame",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Juaben",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Ahafo Ano South East",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Amansie South",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Atwima Nwabiagya North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Akrofuom",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Adansi Asokwa",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Obuasi East",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Afigya Kwabre North",
      regionId: 12,
    ),
    District(
      id: 1,
      code: "",
      name: "Abura Asebu Kwanankese",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Agona East",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Ajumako Enyan Essiam",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Asikuma Odoben Bankwa",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Assin Central",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Assin South",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Awutu Senya East",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Awutu Senya West",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Cape Coast",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Effutu",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Ekumfi",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Gomoa Central",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Gomoa West",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Komenda Edina Eguafo-Abirem",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Mfantseman",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Twifo Atti Morkwa",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Twifo Heman Lower Denkyira",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Upper Denkyira East",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Upper Denkyira West",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Assin North",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Gomoa East",
      regionId: 13,
    ),
    District(
      id: 1,
      code: "",
      name: "Gushegu",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Karaga",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Kpandai",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Kpandai",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Mion",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Nanumba North",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Nanumba South",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Saboba",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Sagnangu",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Sarelugu",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Tamale",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Tatale/Sanguli",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Tolon",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Yendi",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Zabzugu",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Nanton",
      regionId: 14,
    ),
    District(
      id: 1,
      code: "",
      name: "Bawku",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Bawku West",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Binduri",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Bolgatanga",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Bongo",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Builsa North",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Builsa South",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Gani",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Kassena Nankana",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Kassena Nankana West",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Nabdam",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Talensi",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Bolgatanga East",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Tempane",
      regionId: 15,
    ),
    District(
      id: 1,
      code: "",
      name: "Daffiama Bussie Issa",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Jirapa",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Lumbussie Karni",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Lawra",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Nadwoli Kaleo",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Nadom",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Sissala West",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Sissala East",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Wa East",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Wa West",
      regionId: 16,
    ),
    District(
      id: 1,
      code: "",
      name: "Wa",
      regionId: 16,
    ),
  ];

  DistrictRepository({@required this.districtApiClient})
      : assert(districtApiClient != null);

  Future<void> getDistricts() async {
    _districts = await districtApiClient.fetchDistricts();
  }

  List<District> get districts {
    return List.from(_districts);
  }

  List<DropdownMenuItem<District>> getDropdownMenuItems() {
    List<DropdownMenuItem<District>> items = List();

    for (District district in _districts) {
      items.add(DropdownMenuItem(
        value: district,
        child: Text(district.name),
      ));
    }

    return items;
  }

  List<DropdownMenuItem<District>> getDropdownMenuItem() {
    List<DropdownMenuItem<District>> items = List();

    for (District district in _districts) {
      items.add(DropdownMenuItem(
        value: district,
        child: Text(district.name),
      ));
    }

    return items;
  }
}
